import java.util.*

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

val keystorePropertiesFile = rootProject.file("keystore.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(keystorePropertiesFile.inputStream())
}

fun getBuildDate(): String {
    val calendar = Calendar.getInstance()
    val year = calendar.get(Calendar.YEAR)
    val month = calendar.get(Calendar.MONTH) + 1
    val day = calendar.get(Calendar.DAY_OF_MONTH)
    return String.format("%04d%02d%02d", year, month, day)
}

fun getBuildTime(): String {
    val calendar = Calendar.getInstance()
    val hour = calendar.get(Calendar.HOUR_OF_DAY)
    val minute = calendar.get(Calendar.MINUTE)
    return String.format("%02d%02d", hour, minute)
}

// Use system timestamp to generate version code
val timestamp = System.currentTimeMillis()
val generatedVersionCode = (timestamp / 1000).toInt()

// Generate versionName: 1.yyyymmdd.hhmm
val datePart = getBuildDate()
val defaultBuildNumber = getBuildTime()
val buildNumber = project.findProperty("buildNumber") as? String ?: defaultBuildNumber

// ---------------------------------------------------------------------------
// Build-time license info generation
// ---------------------------------------------------------------------------
// The in-app "Licenses" screen reads `com.chronie.gift.data.LicensesData`,
// which is generated here from app/licenses/licenses.json (and the referenced
// .txt files). Editing those config files changes what the screen displays at
// build time, so the license list no longer needs to be hand-maintained inside
// Kotlin source.
val licenseConfigDir = file("licenses")
val licenseGenRoot = file("build/generated/license/kotlin")

val generateLicenseInfo = tasks.register("generateLicenseInfo") {
    val configFile = File(licenseConfigDir, "licenses.json")
    inputs.files(
        fileTree(licenseConfigDir) {
            include("*.json", "*.txt")
        }
    )
    val outFile = File(licenseGenRoot, "com/chronie/gift/data/LicensesData.kt")
    outputs.file(outFile)

    doLast {
        val config = groovy.json.JsonSlurper().parse(configFile) as Map<*, *>
        val libs = config["libraries"] as List<*>

        // Escape a value for emission as a Kotlin double-quoted string literal.
        fun strLiteral(value: String): String =
            "\"" + value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t")
                .replace("$", "\\$") + "\""

        // Emit a license body as a triple-quoted raw string. `$` must be escaped
        // because it would otherwise start a Kotlin string template.
        fun rawString(value: String): String {
            require("\"\"\"" !in value) {
                "License text in $configFile must not contain three consecutive double quotes."
            }
            return "\"\"\"\n" + value.replace("$", $$"${'$}'") + "\n\"\"\""
        }

        val sb = StringBuilder()
        sb.appendLine("package com.chronie.gift.data")
        sb.appendLine()
        sb.appendLine("// AUTO-GENERATED by the generateLicenseInfo Gradle task.")
        sb.appendLine("// Edit app/licenses/licenses.json and the referenced .txt files to change the")
        sb.appendLine("// content shown on the in-app Licenses screen. Do not edit this file by hand.")
        sb.appendLine("object LicensesData {")
        sb.appendLine("    val licenses = listOf(")
        for (rawLib in libs) {
            val lib = rawLib as Map<*, *>
            val name = lib["name"] as String
            val version = lib["version"] as String
            val licenseName = lib["license"] as String
            val url = lib["url"] as String
            val textFile = lib["licenseTextFile"] as String
            val text = File(licenseConfigDir, textFile).readText()
            sb.appendLine("        LicenseInfo(")
            sb.appendLine("            name = ${strLiteral(name)},")
            sb.appendLine("            version = ${strLiteral(version)},")
            sb.appendLine("            license = ${strLiteral(licenseName)},")
            sb.appendLine("            url = ${strLiteral(url)},")
            sb.appendLine("            licenseText = ${rawString(text)}.trimIndent()")
            sb.appendLine("        ),")
        }
        sb.appendLine("    )")
        sb.appendLine("}")
        outFile.parentFile.mkdirs()
        outFile.writeText(sb.toString())
    }
}

android {
    namespace = "com.chronie.gift"
    compileSdk {
        version = release(37)
    }

    signingConfigs {
        create("release") {
            storeFile = keystoreProperties["STORE_FILE"]?.let { file(it as String) }
            storePassword = keystoreProperties["STORE_PASSWORD"] as? String
            keyAlias = keystoreProperties["KEY_ALIAS"] as? String
            keyPassword = keystoreProperties["KEY_PASSWORD"] as? String
        }
    }

    defaultConfig {
        applicationId = "com.chronie.gift"
        minSdk = 24
        targetSdk = 36
        
        // Use generated version code
        versionCode = generatedVersionCode
        versionName = "1.$datePart.$buildNumber"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }
    buildFeatures {
        compose = true
    }

    sourceSets {
        getByName("main") {
            kotlin.srcDirs(licenseGenRoot)
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    // Navigation 3 dependencies
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    // Scopes ViewModels (and their SavedStateHandle) to a single NavEntry
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    // HTTP client libraries
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.android)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    
    // Image loading library
    implementation(libs.coil.compose)
    implementation(libs.coil.network.okhttp)
    
    // Miuix dependencies
    implementation(libs.miuix.ui)
    implementation(libs.miuix.preference)
    implementation(libs.miuix.icons)
    implementation(libs.miuix.blur)
    
    // No longer need Markdown rendering library, we use our own renderer
}

tasks.named("preBuild") {
    dependsOn(generateLicenseInfo)
}